# Generated by Django 4.0.6 on 2022-07-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveBigIntegerField()),
                ('text', models.TextField()),
                ('aftur', models.CharField(max_length=250)),
                ('dete_added', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
                ('categoriya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoriya')),
            ],
        ),
    ]
